/**
 * Centralized error IDs for tracking and monitoring
 * Use these IDs with logError to track error patterns in production
 */
export const ErrorIds = {
  // Auth errors
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Database errors
  DB_READ_FAILED: 'DB_READ_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_DELETE_FAILED: 'DB_DELETE_FAILED',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',

  DIGEST_SEND_FAILED: 'DIGEST_SEND_FAILED',
  DIGEST_QUERY_FAILED: 'DIGEST_QUERY_FAILED',

  // Budget/Finance errors
  BUDGET_CREATE_FAILED: 'BUDGET_CREATE_FAILED',
  BUDGET_UPDATE_FAILED: 'BUDGET_UPDATE_FAILED',
  BUDGET_DELETE_FAILED: 'BUDGET_DELETE_FAILED',
  EXPENSE_CREATE_FAILED: 'EXPENSE_CREATE_FAILED',
  EXPENSE_UPDATE_FAILED: 'EXPENSE_UPDATE_FAILED',
  EXPENSE_DELETE_FAILED: 'EXPENSE_DELETE_FAILED',
  INCOME_CREATE_FAILED: 'INCOME_CREATE_FAILED',
  INCOME_UPDATE_FAILED: 'INCOME_UPDATE_FAILED',
  INCOME_DELETE_FAILED: 'INCOME_DELETE_FAILED',
  CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
  CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',
  ACCOUNT_CREATE_FAILED: 'ACCOUNT_CREATE_FAILED',
  ACCOUNT_UPDATE_FAILED: 'ACCOUNT_UPDATE_FAILED',
  ACCOUNT_DELETE_FAILED: 'ACCOUNT_DELETE_FAILED',
  FATURA_OPERATION_FAILED: 'FATURA_OPERATION_FAILED',
  BUCKET_UPDATE_FAILED: 'BUCKET_UPDATE_FAILED',
  BUDGET_CONFIG_UPDATE_FAILED: 'BUDGET_CONFIG_UPDATE_FAILED',
  SAFE_TO_SPEND_CALCULATION_FAILED: 'SAFE_TO_SPEND_CALCULATION_FAILED',

  // Import errors
  IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',
  IMPORT_VALIDATION_FAILED: 'IMPORT_VALIDATION_FAILED',
  IMPORT_SAVE_FAILED: 'IMPORT_SAVE_FAILED',

  // Billing errors
  BILLING_EMAIL_SEND_FAILED: 'BILLING_EMAIL_SEND_FAILED',
  BILLING_WEBHOOK_SIGNATURE_FAILED: 'BILLING_WEBHOOK_SIGNATURE_FAILED',
  BILLING_WEBHOOK_HANDLER_FAILED: 'BILLING_WEBHOOK_HANDLER_FAILED',
  BILLING_RENEWAL_REMINDER_FAILED: 'BILLING_RENEWAL_REMINDER_FAILED',
  BILLING_STRIPE_FETCH_FAILED: 'BILLING_STRIPE_FETCH_FAILED',
  BILLING_USAGE_EMAIL_FAILED: 'BILLING_USAGE_EMAIL_FAILED',

  // User settings errors
  SETTINGS_UPDATE_FAILED: 'SETTINGS_UPDATE_FAILED',
  SETTINGS_READ_FAILED: 'SETTINGS_READ_FAILED',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Generic errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export type ErrorId = typeof ErrorIds[keyof typeof ErrorIds];
